version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: listen
    versions:
    - 3.4.0
    - 3.4.1
  - dependency-name: nokogiri
    versions:
    - 1.11.0
    - 1.11.1
  - dependency-name: capybara
    versions:
    - 3.34.0
  - dependency-name: jbuilder
    versions:
    - 2.10.1
